# Punto 1

In [90]:
import numpy as np
import matplotlib.pyplot as plt

In [91]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [92]:
np.linalg.solve(M,b)

array([1., 1., 1.])

In [93]:
def GetacobiMethod(A,b,itmax=1000,error = 1e-10):
    
    M,N = A.shape
    
    P = np.zeros(N)

    sumk = np.zeros_like(P)
    
    x=0
    y=0
    z=0
    
    P = [x,y,z]
    
    it = 0
    
    residuo = np.linalg.norm( b - np.dot(A,P) )
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*P[j]
            sumk[i] = sum_
          
        for i in range(M):
            
            if A[i,i] != 0:
                P[i] = (b[i] - sumk[i])/A[i,i]
                x=(b[0]-A[0,1]*y-A[0,2]*z)/A[0,0]
                y=(b[1]-A[1,0]*x-A[1,2]*z)/A[1,1]
                z=(b[2]-A[2,0]*x-A[2,1]*y)/A[2,2]
                P = [x,y,z]
            else:
                print('No invertible con Jacobi')
        
        print(P)
        residuo = np.linalg.norm(b - np.dot(A,P))
        
    return P,it,residuo

In [94]:
Xsol,it,error = GetacobiMethod(M,b)

[0.9629629629629631, 1.006172839506173, 1.016975308641975]
[1.0004286694101507, 0.9998285322359397, 0.9998285322359397]
[0.9999936493420719, 1.0000010584429881, 1.000002910718217]
[1.0000000735029853, 0.9999999705988057, 0.9999999705988061]
[0.999999998911067, 1.0000000001814888, 1.0000000004990943]
[1.0000000000126033, 0.9999999999949587, 0.9999999999949587]


# Punto 2

In [95]:
import numpy as np
import matplotlib.pyplot as plt

In [96]:
def GetMethods(A,b,itmax=1000,error = 1e-10):
    
    print("Metodo Jacobi:")
    
    M,N = A.shape
    
    x = np.zeros(N)
    
    sumk = np.zeros_like(x)
    
    
    it = 0
    
    residuo = np.linalg.norm( b - np.dot(A,x) )
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*x[j]
            sumk[i] = sum_
          
        for i in range(M):
            
            if A[i,i] != 0:
                x[i] = (b[i] - sumk[i])/A[i,i]
            else:
                print('No invertible con Jacobi')
        
        print(x)
        residuo = np.linalg.norm( b - np.dot(A,x) )
        
    print("Número de iteraciones:" +str(it))
    
    print("Método Gaus-Seidel")
    
    M,N = A.shape
    
    P = np.zeros(N)

    sumk = np.zeros_like(P)
       
    it = 0
    
    residuo = np.linalg.norm( b - np.dot(A,P) )
    
    while ( residuo > error and it < itmax ):
        
        it += 1
        
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*P[j]
            sumk[i] = sum_
          
        for i in range(M):
            
            if A[i,i] != 0:
                P[i] = (b[i] - sumk[i])/A[i,i]
                
                for l in range(0,N):
                    sumatoria = 0
                    for m in range(0,N):
                        sumatoria += A[l,m]*P[m]
                        
                    P[l]=(b[l]-(sumatoria-(A[l,l]*P[l])))/A[l,l]
                    
                    
                
                
                
            else:
                print('No invertible con Jacobi')
        
        print(P)
        residuo = np.linalg.norm(b - np.dot(A,P))
        

    
    print("Número de iteraciones:" +str(it))
    
    return P,it,residuo

In [97]:
Xsol,it,error = GetMethods(M,b)

Metodo Jacobi:
[0.33333333 1.         1.75      ]
[1.25       0.52777778 1.33333333]
[0.9537037  0.97222222 0.99305556]
[0.98842593 0.98688272 1.03009259]
[1.00565844 0.98611111 1.00906636]
[0.99839249 0.99886403 1.000643  ]
[0.99983568 0.99924983 1.00108775]
[1.00011253 0.99958264 1.0002697 ]
[0.99995078 0.99994761 1.00004808]
[0.99999856 0.99996757 1.00003771]
[1.00000176 0.99998695 1.00000883]
[0.99999859 0.99999764 1.00000238]
[1.00000001 0.99999874 1.00000129]
[1.00000001 0.99999957 1.00000031]
[0.99999996 0.9999999  1.0000001 ]
[1.         0.99999995 1.00000004]
[1.         0.99999999 1.00000001]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Número de iteraciones:23
Método Gaus-Seidel
[1.22736626 0.82578875 0.92986968]
[0.97720961 1.01577997 1.0074502 ]
[1.00239866 0.99831615 0.99922163]
[0.99974911 1.00017583 1.00008149]
[1.00002626 0.99998159 0.99999147]
[0.99999725 1.00000193 1.00000089]
[1.00000029 0.9999998  0.99999991]
[0.99999997 1.00000002 1.00000001]


# Punto 3

In [98]:
import numpy as np
import matplotlib.pyplot as plt

In [102]:
def GetMethods(A,B): 
    
    MA,NA = A.shape
    MB,NB = B.shape
    C = np.zeros((MA, NB))
    
    
    if NA == MB:
        for i in range(0,MA):
            for j in range(0,NB):
                C[i,j] = 0
                for k in range(0,NA):
                    C[i,j] += (A[i,k]*B[k,j])
        print(C)
    else:
        print("Dimensiones no adecuadas")
        
                    
                
    
    
 

In [103]:
A = np.array([[3,-1,-1,2],[-1,3,1,3],[2,1,4,4],[2,3,4,6]])
B = np.array([[3,0,-1],[-1,0,1],[2,0,4],[-1,4,3]])

In [106]:
GetMethods(A,B)

[[ 6.  8. -2.]
 [-7. 12. 17.]
 [ 9. 16. 27.]
 [ 5. 24. 35.]]
